WebProject/Controllers/ChangePwdController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using WebProject.Common;
using WebProject.InputModel;
using WebProject.Models;
using WebProject.ViewModel;
using WebProject.BLL;

namespace WebProject.Controllers
{
    [Authorize]
    public class ChangePwdController : Controller
    {
        private readonly UserService helper;
        private readonly IHttpContextAccessor context;
        public ChangePwdController(UserService _helper,IHttpContextAccessor _context)
        {
            helper = _helper;
            context = _context; 
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePassword([FromForm] ModifyPwdInfoIM ModifyCondition)
        {
            string Email = Base.Get<UserInfoVM>(context.HttpContext.Session, "UserInfo")==null?"": Base.Get<UserInfoVM>(context.HttpContext.Session, "UserInfo").Email;
            string result = await helper.UpdateUserPwd(Email, ModifyCondition.NewPassword, ModifyCondition.OldPassword);
            if (string.IsNullOrEmpty(result)) return Ok("密碼修改成功");
            else return BadRequest(result); 
        }
    }
}

WebProject/Views/ChangePwd/Index.cshtml
@{
    ViewData["Title"] = "";
}

<div class="row">
    <div class="card">
        <div class="card-header">更改密碼</div>
    </div>
    <div class="card-body">
        @using(Html.BeginForm()){
            @Html.AntiForgeryToken()
        <div class="row">
            <label class="form-label col-sm-2">舊密碼</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="OldPassword" onblur="CheckPwd(this)" required />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <label class="form-label col-sm-2">新密碼</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="NewPassword" onblur="CheckPwd(this)" required />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <label class="form-label col-sm-2">確認密碼</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ConfirmPassword" onchange="CompareValidPwd(this)" required />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="d-flex justify-content-center mt-3">
            <input type="button" class="btn btn-outline-success" value="確定修改" id="btnUpdate"/>
        </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
       $("#btnUpdate").click(function(){
           
            if (!CheckPassword($("#OldPassword").val()) || !CheckPassword($("#NewPassword").val())) {
                SweetAlert('error', '請輸入6位以上，包含英文與數字，但不包含特殊符號',1500);
                return;
            }

            if (!ComparePwd()){
                SweetAlert('error', '新密碼請與確認密碼一致', 1500);
                return;
            }
            
            var condition=new Object();
            condition.OldPassword = $("#OldPassword").val();
            condition.NewPassword = $("#NewPassword").val();
            $.ajax({
                url: "@Url.Action("UpdatePassword","ChangePwd")",
                type:"POST",
                data:{
                    ModifyCondition:condition
                },
                headers:{
                    RequestVerificationToken: $("input[name='__RequestVerificationToken']").val(),
                },
                success:function(data){
                    SweetAlert("success", "密碼修改成功", 1500);
                },
                error:function(error){
                    SweetAlert("error", error.responseText, 1500);
                }
            })

       });
    });

    function CheckPwd(obj){
        var value=$(obj).val(); 
        var element=$(obj).parent().find("span");
        if(!CheckPassword(value)){
            $(element).text("請輸入6位以上，包含英文與數字，但不包含特殊符號");
        }else{
            $(element).text("");
        }
    }

    function CompareValidPwd(obj) {
        var element = $(obj).parent().find("span");
        if(!ComparePwd()) {
            $(element).text("新密碼請與確認密碼一致");
        }else{
            $(element).text("");
        }
    }
</script>