WebProject/Controllers/FoodController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebProject.BLL;
using WebProject.Filter;

namespace WebProject.Controllers
{
    [Authorize]
    [ActionFilter]
    public class FoodController : Controller
    {
        private readonly DeliciousService helper;
        public FoodController(DeliciousService _helper)
        {
            helper = _helper;
        }
        public  IActionResult Index()
        {
            return View();
        }

        //美食地圖 資料量大不跟location放成一個ViewModel
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetFoodInfo()
        {
            var info =await helper.GetTaiwanDelicios();
            if (info.Count > 0) return Ok(info);
            return BadRequest("No Data");
        }

        //get taiwan city
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetCity()
        {
            var result=await helper.GetTaiwanCity();   
            if(result!=null) return Ok(result);
            return BadRequest("No Data");
        }
    }
}

WebProject/Views/Food/Index.cshtml
@{
    ViewData["Title"] = "美食地圖";
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD1ZrNyzoKC0rglW3qiJWwEsPOIN08Hoio&callback=initMap"></script>
<script src="~/public/kuan_dll/gmaps.js"></script>
@using (Html.BeginForm())
{
    <div class="card">
        <div class="card-header">
            美食地圖
        </div>
        <div class="card-body">
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col">
                    <label class="form-label">城市:</label>
                    <select id="dplCity"></select>
                </div>
            </div>
            <div class="col-md-12 col-lg-12 col-xl-12">
                <div class="ratio ratio-16x9">
                    <div id="map"></div>
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    var foodInfo;
    var map;
    $(document).ready(function () {
        GetTaiwanCity();
        GetFoodInfo();
        initMap();
        $("#dplCity").change(function () {
            var filterMap = foodInfo.filter(x => x.Add.includes($(this).val()));
            RemarkMap(filterMap);
        });
    });

    function GetFoodInfo() {
        $.ajax({
            url: "@Url.Action("GetFoodInfo","Food")",
            type: "POST",
            headers: {
                RequestVerificationToken: $("input[name='__RequestVerificationToken']").val(),
            },
            success: function (data) {
                if (data.length > 0) {
                    foodInfo = data;
                }
            },
            error: function (error) {
                SweetAlert("error", error.responseText, 1500);
            },
            beforeSend: function () {
                foodInfo = [];
            }
        })
    }

    function GetTaiwanCity() {
        $.ajax({
            url: "@Url.Action("GetCity","Food")",
            type: "POST",
            headers: {
                RequestVerificationToken: $("input[name='__RequestVerificationToken']").val(),
            },
            success: function (data) {
                $("#dplCity").html("");
                var html = "<option value=''>==請選擇地區==</option>";
                $.each(data, function (index, item) {
                    html += "<option value='" + item + "'>" + item + "</option>";
                });
                $("#dplCity").append(html);
                $("#dplCity").selectpicker();
            },
            error: function (error) {
                SweetAlert("error", error.responseText, 1500);
            }
        });
    }

    function RemarkMap(mapInfo) {
        var location = {
            lat: mapInfo[0].Py,
            lng: mapInfo[0].Px,
        };
        map = new GMaps({
            div: '#map',
            zoom: 16,
            lat: location.lat,
            lng: location.lng,
            mapTypeId: "satellite"
        });
        $.each(mapInfo, function (index, item) {
            map.addMarker({
                lat: item.Py,
                lng: item.Px,
                title: item.Name,
                infoWindow: {
                    content: "<div class='col-sm-12 col-md-12 col-lg-12'><div class='card'><div class='card-header'>" + item.Name + "</div><img class='card-img-top' src='" + item.Picture1 + "'><div class='card-body'><div class='card-text'><div class='row'><font>地址:" + item.Add + "</font></div><div class='row'><font>開店時間:" + item.Opentime + "</font></div></div></div></div><div>"
                }
            });
        });
    }


    function initMap() {
        map = new GMaps({
            div: "#map",
            zoom: 16,
            lat: 25.0338041,
            lng: 121.5623674,
            mapTypeId: "satellite"
        })
    }
</script>